site_name: Robostorm
site_dir: /var/www/html/mkdocs-site
repo_url: https://github.com/Robostorm
theme: flatly
site_favicon: icon.png
pages:
- Home: 'index.md'
- Projects:
    - 'Aquabot': 'aquabot.md'
    - 'Aquaponics': 'aquaponics.md'
    - '3D Printer': '3dprinter.md'
    - 'Other Projects': 'projects.md'
- Battlebots: 'battlebots.md'
- About Us:
    - 'Contact Us': 'contact.md'
    - 'History': 'history.md'
- Members Only: 'lock/members.md'